skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dom_vault = "9QCZ5TyJeZEToPUDtitiCNvsxCs33gVPjm4XTCK2vv8b"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
